default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'db' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'foo' } %>
  password: <%= ENV.fetch('DATABASE_PASS') { 'bar' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { 'db' } %>
test:
  <<: *default
  database: app_test

production:
  url: <%= ENV['DATABASE_URL'] %>
